apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canteen-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - midden.reedgaines.com
    secretName: canteen-midden-tls-secret
  rules:
  - host: midden.reedgaines.com
    http:
      paths:
      - path: /canteen(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: canteen-service
            port:
              number: 3000